--!strict
--[=[
	@class QueryAuth
	fully type-safe permissions module for Roblox Luau.

	For more information, check out the GitHub: https://github.com/PossiblePanda/QueryAuth
]=]

local QueryAuthTypes = require(script.Types)

local DefaultAuthConditionsFolder = script.DefaultAuthConditions

local QueryAuth = {}

type AuthCondition = QueryAuthTypes.AuthCondition
type Policy = QueryAuthTypes.Policy

export type QueryAuthModule = {
	Team: (values: string?) -> AuthCondition,
	UserId: (values: number?) -> AuthCondition,
	Policy: (policy: Policy) -> AuthCondition,
	Studio: () -> AuthCondition,
	Premium: () -> AuthCondition,
	AccountAge: (minimum: number, maximum: number?) -> AuthCondition,
	Gamepass: (gamepassId: number) -> AuthCondition,
	Group: (group_id: number, min_rank: number? | string?, max_rank: number? | string?) -> AuthCondition,
	Badge: (values: number?) -> AuthCondition,
	FriendsWith: (otherPlayerId: number) -> AuthCondition,
	ServerTime: (time: number) -> AuthCondition,
	Throttle: (time: number, mark: (() -> number)?) -> AuthCondition,
	GlobalThrottle: (time: number, mark: (() -> number)?) -> AuthCondition,
	Once: () -> AuthCondition,

	all: (conditions: { AuthCondition }) -> AuthCondition,
	one: (conditions: { AuthCondition }) -> AuthCondition,
	has: (amount: number, conditions: { AuthCondition }) -> AuthCondition,
	negate: (condition: AuthCondition) -> AuthCondition,
}

--[=[
	Combines multiple AuthConditions and only passes if *all* conditions are true.
	@param conditions {AuthCondition} -- List of conditions to evaluate.
	@return AuthCondition -- A lambda that evaluates to see if ALL conditions are true.
]=]
function QueryAuth.all(conditions: { AuthCondition }): AuthCondition
	return function(player: Player): boolean
		for _, condition in conditions do
			if not condition(player) then
				return false
			end
		end
		return true
	end
end

--[=[
	Combines multiple AuthConditions and only passes if *any* condition is true.
	@param conditions {AuthCondition} -- List of conditions to evaluate.
	@return AuthCondition -- A lambda that evaluates to see if ANY conditions are true.
]=]
function QueryAuth.any(conditions: { AuthCondition }): AuthCondition
	return QueryAuth.has(1, conditions)
end

--[=[
	Combines multiple AuthConditions and only passes if *amount* conditions are true.
	@param amount number -- The amount of conditions that must pass.
	@param conditions {AuthCondition} -- List of conditions to evaluate.
	@return AuthCondition -- A lambda that evaluates to see if the amount of conditions are true.
]=]
function QueryAuth.has(amount: number, conditions: { AuthCondition }): AuthCondition
	return function(player: Player): boolean
		local passed = 0
		for _, condition in conditions do
			if not condition(player) then
				continue
			end

			passed += 1
			if passed >= amount then
				return true
			end
		end
		return false
	end
end

--[=[
	Returns true if the AuthCondition is false.
	@param condition AuthCondition -- The condition to negate.
	@return AuthCondition -- A lambda that negates the provided condition.
]=]
function QueryAuth.negate(condition: AuthCondition): AuthCondition
	return function(player: Player)
		return not condition(player)
	end
end

-- Add auth functions
QueryAuth.Team = require(DefaultAuthConditionsFolder.Team)
QueryAuth.UserId = require(DefaultAuthConditionsFolder.UserId)
QueryAuth.Policy = require(DefaultAuthConditionsFolder.Policy)
QueryAuth.Studio = require(DefaultAuthConditionsFolder.Studio)
QueryAuth.Premium = require(DefaultAuthConditionsFolder.Premium)
QueryAuth.AccountAge = require(DefaultAuthConditionsFolder.AccountAge)
QueryAuth.Gamepass = require(DefaultAuthConditionsFolder.Gamepass)
QueryAuth.Group = require(DefaultAuthConditionsFolder.Group)
QueryAuth.Badge = require(DefaultAuthConditionsFolder.Badge)
QueryAuth.FriendsWith = require(DefaultAuthConditionsFolder.FriendsWith)
QueryAuth.ServerTime = require(DefaultAuthConditionsFolder.ServerTime)
QueryAuth.GlobalThrottle = require(DefaultAuthConditionsFolder.GlobalThrottle)
QueryAuth.Throttle = require(DefaultAuthConditionsFolder.Throttle)
QueryAuth.Once = require(DefaultAuthConditionsFolder.Once)

return QueryAuth :: QueryAuthModule
